version: '2'
services:
  api:
    build: .
    command: /bin/sh -c "npm run migrate && npm run start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: rytmi
      DB_PASSWORD: rytmi
      DB_NAME: rytmi
  postgres:
    image: postgres:10.2-alpine
    environment:
      POSTGRES_USER: rytmi
      POSTGRES_PASSWORD: rytmi
      POSTGRES_DB: rytmi